### ISSUE TITLE
Missing the GSAP module instructions

### ISSUE THREAD

**Issue by jonaswebdev** [kugatsu765/vueNotification#1]
Hi I installed this module (vueNotification) but got a error message`Module not found: Error: Can't resolve 'gsap' in '/var/www/html/node_modules/@kugatsu/vuenotification/dist'`.

I solved it installing the module GSAP but is missing instruction in the documentation about it or another way is to include as dependence on this module.

**Comment by kugatsu765** [comment]
Thanks, i will add this part to the doc.
