### ISSUE TITLE
Make possible to change position of notification from absolute to fixed

### ISSUE THREAD

**Issue by hbarcelos** [kugatsu765/vueNotification#13]
The problem arises when using notifications in a really long page.

I currently have the position set to `bottomRight`. When I scroll up, the notification will be scrolled out. This is not always the desired behavior.

Would it be possible to allow for a configuration setting `.notificationCenter` position to `fixed`?

**Comment by kugatsu765** [comment]
Hy, i notice that too. I will update the package on monday.

Thanks for using it and Share your issue.

**Comment by kugatsu765** [comment]
Hy, i pubished yesterday oon NPM the version 1.1.3 to fix the issue.
