### ISSUE TITLE
Error Gsap TimelineMax is not defined 

### ISSUE THREAD

**Issue by DrazahSuzaku** [kugatsu765/vueNotification#21]
I had declared properly the import and the Vue Use. 

I have this error only if a specify the _animateIn_ in the Vue.use.

When i call the notification in a Vue component, the notification works as expected but an error appear in the debug console :

[Vue warn]: Error in mounted hook: "ReferenceError: TimelineMax is not defined"
(found in <Root>)

**Comment by kugatsu765** [comment]
Hello, gasp is not include in the dependency so you have to download by yourself. 
With yarn add gsap or Npm install. It should work correctly.

**Comment by DrazahSuzaku** [comment]
> Hello, gasp is not include in the dependency so you have to download by yourself.
> With yarn add gsap or Npm install. It should work correctly.

Sorry for the delay, covid problematics etc...

Like i said, i import Gsap properly. This is not the problem.

**Comment by wanghongting** [comment]
Hello, how to introduce TweenMax and TimelineMax in vue
