### ISSUE TITLE
Is HTML support added in it?

### ISSUE THREAD

**Issue by ChaudharyHabib** [kugatsu765/vueNotification#54]
HTML not working!

this.$notification.success("<strong>hello world</strong>");

**Comment by ChaudharyHabib** [comment]
I checked your source, yes it's added but you didn't mention it in the docs.

```
Vue.use(VueNotification, {
    timer: 20,
    messageIsHTML: true,
});
```

**Comment by kugatsu765** [comment]
Thanks, i will add it :)
